# -*- coding: utf-8 -*-
"""ecommerce-data-analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-pTq6D350q5LmdVpiIF-zh1TIzRsv0kw

# Jawablah poin-poin assignment berikut
#### perhatikan dengan baik apa yang diminta pada soal

# 1. Anda bekerja sebagai seorang data scientist, atasan anda mengirimkan anda data kepada anda dan meminta untuk memberikan analisa dengan menggunakan :
- semua metode pada proses Exploratory Data Analysis. Lakukan proses Feature Engineering terlebih dahulu dan mengecek secara teliti pada tiap kolom data sembari melakukan data understanding. **(20 Poin)**

#Import dan membaca data
"""

# Commented out IPython magic to ensure Python compatibility.
from scipy.stats import norm
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import seaborn as sns
# %matplotlib inline

from sklearn.preprocessing import MultiLabelBinarizer

df = pd.read_csv('/content/ecommerce.csv')

"""#Data Understanding"""

df.head()

df.describe().T

df.shape

df.info()

df = df.drop(columns=['InvoiceNo', 'CustomerID'])

"""Kolom InvoiceNo dan CustomerID dibuang karena kolom ini berbentuk numerik, tetapi bukan data kuantitatif sebenarnya

Cek duplikat data
"""

df.duplicated().sum()

"""Cek missing values"""

df.isnull().sum()

missing_percentage = df.isnull().sum()/df.shape[0]*100
missing_percentage.sort_values(ascending=False)

df['TotalPrice'] = df['Quantity'] * df['UnitPrice']
df[['Quantity', 'UnitPrice', 'TotalPrice']].describe()

"""Hal ini dilakukan untuk menciptakan variabel baru yang merepresentasikan nilai transaksi dan menganalisis statistik deskriptif atas metrik-metrik utama transaksi. Singkatnya manfaatnya adalah untuk Mengetahui berapa nilai transaksi yang sebenarnya dilakukan, bukan hanya jumlah barang atau harga unit. Dari sini kita bisa ambil rata-rata pembelian per transaksi, variasi harga produk, transaksi maksimum/minimum.

Cek outlier dari kolom numerik
"""

numeric_cols = df.select_dtypes(include=np.number).columns

for col in numeric_cols:
    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)
    IQR = Q3 - Q1
    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR

    outliers = df[(df[col] < lower_bound) | (df[col] > upper_bound)]
    outlier_count = len(outliers)
    outlier_percentage = (outlier_count / len(df)) * 100
    print(f"{col}: {outlier_count} outliers ({outlier_percentage:.2f}%)")

"""Untuk Outlier akan dibiarkan untuk kebutuhan analisis.

Selanjutnya karena tidak ada missing values dan data terduplikat, maka kita akan pastikan abhwa di dalam data tidak ada multilabels
"""

# Cek baris yang kemungkinan merupakan header duplikat
suspect_rows = df[df.apply(lambda row: row.astype(str).str.contains("InvoiceNo|Description|Quantity", case=False).any(), axis=1)]

# Tampilkan baris yang mencurigakan
print("Baris yang mencurigakan sebagai header duplikat atau tabel bertumpuk:")
print(suspect_rows)

"""Digunakan kolom 'InvoiceNo', 'Description', dan 'Quantity' karena ketiga kolom tersebut dinilai rawan dalam multilable. Tetapi Index yang muncul menandakan bahwa tidak ada kolom yang multilable

#Feature Engineering

PS: keterangannya semua ada di masing-masing nomor, kenapa harus dilakukan sesuai dengan peruntukkannya masing-masing
"""

# Hapus baris dengan missing values pada kolom penting
df_clean = df.dropna(subset=["Description", "Quantity", "InvoiceDate", "Country"])

# Konversi InvoiceDate ke datetime
df_clean["InvoiceDate"] = pd.to_datetime(df_clean["InvoiceDate"])

# Buat kolom baru: Bulan transaksi
df_clean["Month"] = df_clean["InvoiceDate"].dt.to_period("M").astype(str)

# (Opsional) Kolom jumlah pembelian (Quantity * UnitPrice)
df_clean["TotalPrice"] = df_clean["Quantity"] * df_clean["UnitPrice"]

# Simpan hasil feature engineering
df_ready = df_clean.copy()

# Tampilkan hasil akhir (siap dipakai untuk analisis)
display(df_ready.head())

"""# 2. Setelah melakukan feature engineering, Ikuti anjuran berikut :
- Buat 5 pertanyaan analisa
- jawab dengan pendekatan metode data manipulation (sorting, filtering, group by, pivot, melt, crosstab, working with datetime, dsb (sesuaikan dengan keperluan anda
- Buatlah visualisasi grafik supaya mempermudah dalam ekstraksi insight setelah menjawab menggunakan metode data manipulation diatas
- Tulis insight anda

`poin` :
- insight / observation : **10 poin (1 pertanyaan 2 poin)**
- pertanyaan analisis dan jawaban metode data manipulation : **30 poin (1 pertanyaan 7 poin)**
- data visualisasi : **30 poin (1 visualisasi dari 1 pertanyaan 7 poin)**

#Q1. Produk apa yang paling sering dibeli dalam jumlah besar (Quantity > 10)?

Sebelumnya kita harus tau datanya dulu sebelum mulai filtering. Pada kasus ini kita membutuhkan 2 kolom, yaitu: 'Description' dan 'Quantity'. Hal ini dikarenakan kita ingin mengetaui junmlah dari deskripsi produk yang memiliki kemungkinan untuk dibeli dalam jumlah besar
"""

df_before = df[["Description", "Quantity"]].head(10)
df_before

df_filtered = df[df["Quantity"] > 10]
df_after = df_filtered[["Description", "Quantity"]].head(10)
df_after

"""Dapat dilihat bahwa pada table pertama bahwa data yang disajikan acak, sehingga menjadi sulit dipahami dan kurang relevan. Setelah dilakukan filtering, data pertama berubah menjadi data pada table kedua yang mana data yang disajikan menjadi lebih tertata dan relevan. Lebih lanjut, pada pada tabel kedua hanya menampilkan data pembelian produk dalam jumlah diatas 10."""

top_products = df_ready.groupby("Description")["Quantity"].sum().sort_values(ascending=False).head(10).reset_index()
top_products

"""Agregasi menggunakan sum() yang kemudian menunjukkan table diatas dilakukan karena adanya kemungkinan satu produk yang bisa muncul dalam banyak transaksi dengan kuantitas yang berbeda. Hal ini membuat penjumlahan pada total Quantity untuk setiap produk menjadi perlu demi identifikasi produk mana yang secara keseluruhan paling banyak dibeli dalam jumlah besar (lebih dari 10 unit per transaksi). Ini membantu mengungkap pola permintaan massal yang relevan untuk strategi bisnis seperti penawaran grosir, bundling, atau penyediaan stok besar. Jika hanya melihat per baris transaksi tanpa agregasi, kita tidak akan mendapatkan gambaran lengkap tentang produk mana yang paling dominan dalam volume pembelian. <br> <br>

Pada kode diatas juga diurutkan dari yang terbanyak demi kenyaman dalam analisis data
"""

sns.barplot(data=top_products, x="Quantity", y="Description", palette="viridis")
plt.title("Top 10 Produk dengan Penjualan Tertinggi (Total Quantity)")
plt.xlabel("Total Quantity")
plt.ylabel("Nama Produk")
plt.tight_layout()
plt.show()

"""#Insight:
1. Permintaan massal terfokus pada item tertentu – Produk yang muncul di daftar teratas cenderung merupakan barang yang:
  - Kemungkinan digunakan untuk reseller, event, atau paket bundling.

2. Volume penjualan produk tidak selalu sejalan dengan jumlah transaksi: Produk dengan volume besar belum tentu paling sering muncul dalam transaksi; bisa jadi satu pelanggan membeli dalam jumlah besar.

3. Peluang bundling dan penawaran grosir dimana produk-produk ini cocok untuk strategi:
  - Diskon grosir
  - Promosi beli banyak lebih murah
  - Target untuk pelanggan bisnis (B2B)

#Q2. Bagaimana tren pembelian per bulan selama tahun berjalan?

Sebelumnya kita harus mengetahui isi data tersebut dengan data mentah dibawah ini untuk mengetahui data apa yang kita olah. Pada kasus kali ini, gunakan kolom 'InvoiceDate' dan 'Quantity' untuk menggambarkan dengan lebih jelas mengenai produk yang akan laku dipasaran dalam lingkup per masing-masing bulan selama satu tahun.
"""

df_before = df[["InvoiceDate", "Quantity"]].head(5)
df_before

"""Seperti yang terlihat pada tabel pertama yang merupakan data mentah, data tersebut kurang bisa dibaca dengan baik, terutama untuk melakukan visualisasi dimana dibutuhkan manipulasi data secara lebih efisien."""

df["InvoiceDate"] = pd.to_datetime(df["InvoiceDate"], errors='coerce')

"""Kolom 'InvoiceDate' pada tabel pertama, akan dibaca sebagai string, maka kita akan mengubahnya menjadi datetime demi efektivitas manipulasi dan visualisasi data."""

df["Month"] = df["InvoiceDate"].dt.to_period("M")

"""Perlakuan pembentukan kolom berdasarkan bulan ini dilakukan untuk efektivitas dalam manipulasi data. Meskipun kolom 'InvoiceDate' sudah mencakup informasi hingga detik, tetap dinilai tidak efektif karena data yang dibutuhkan adalah data berupa 'bulan-tahun'. Perlakuan ini dilakukan demi efektivitas dalam pembentukkan 'groupby' demi mencapai tujuan analisis berupa 'tren pembelian bulanan selama satu tahun'"""

df_after = df[["InvoiceDate", "Month", "Quantity"]].head(5)
df_after

"""Tabel diatas adalah contoh data (5 data teratas) dari data yang siap digunakan"""

monthly_trend = df_ready.groupby("Month")["Quantity"].sum().reset_index()

"""Hal ini dilakukan untuk dilakukan untuk melakukan pengelompokkan per bulan agar bisa dihitung total pembeliannya, dimana agregasi yang dilakukan mampu menunjukkan  volume pembelian tiap bulan secara keseluruhan. <br><br>
Disinilah fungsi 'convert for plotting' demi kenyamanan visualisasi karena kolom 'Month' bertipe 'period' sehingg harus dibuat menjadi 'string' supaya terlihat jelas sumbu x-nya pada visualisasi data.
"""

plt.figure(figsize=(8, 4))
sns.lineplot(data=monthly_trend, x="Month", y="Quantity", marker="o", linewidth=2.5)
plt.title("Tren Pembelian per Bulan")
plt.xlabel("Bulan")
plt.ylabel("Total Quantity")
plt.ylim(bottom=0)
plt.xticks(rotation=45)
plt.grid(True, linestyle='--', alpha=0.6)
plt.tight_layout()
plt.show()

"""#Insight:
1. Adanya fluktuasi tren pembelian bulanan dimana beberapa bulan menunjukkan lonjakan tajam dalam jumlah pembelian, sementara bulan lainnya cenderung lebih rendah.
  - Lonjakan tersebut bisa disebabkan oleh musim belanja, promosi besar, atau periode stok ulang pelanggan.

2. Penurunan di bulan tertentu bisa menunjukkan masalah atau momen sepi, contohnya: bulan libur panjang, gangguan operasional, atau berkurangnya kampanye pemasaran.

3. Tren ini penting untuk perencanaan bisnis untuk mengetahui pola bulanan membantu dalam:
  - Menyusun strategi stok dan logistik secara efisien
  - Menentukan waktu terbaik untuk promosi
  - Mengantisipasi periode sepi dengan strategi penjualan baru

#Q3. Negara mana yang memiliki volume pembelian terbesar?

Sebelumnya perlu sample data mentah dari kolom 'Country' dan 'Quantity' untuk melihat negara beserta jumlah pembelian yang dilakukan oleh masing-masing negara
"""

df_before = df[["Country", "Quantity"]].head()
df_before

"""Dari table diatas terlihat bahwa meskipun hanya 5 data teratas, tetapi cukup sulit dibaca, lebih lagi untuk dilakukan manipulasi dan analisis serta visualisai untuk melihat pembelian yang dilakukan masing-masing negara."""

country_sales = df_ready.groupby("Country")["Quantity"].sum().sort_values(ascending=False).head(10).reset_index()

"""Grouping pada kode diatas dilakukan untuk membantu menyederhanakan data agar bisa dianalisis secara strategis.Karena setiap baris mewakili satu transaksi, kita perlu mengelompokkan data berdasarkan negara agar bisa melihat total pembelian secara keseluruhan. Tanpa proses ini, kita hanya melihat data transaksi individual, bukan gambaran besar per negara. Lebih lanjut, data dari group by ini mampu digunakan untuk menganalisis potensi pasar dan strategi distribusi."""

df_after = country_sales.head()
df_after

"""Tabel diatas menunjukkan perbedaan signifikan dengan tabel pertama, dimana pada tabel ini menyajikan dalam bentuk pengelompokkan jumlah barang yang dibeli dari satu negara berdasarkan quantity barang yang dibeli. Cukup berbeda dengan data mentah sebelumnya, dimana data tersebut dihitung secara terpisah bukan berkelompok. Terutama disajikan dalam bentuk pengurutan 5 negara terbanyak demi kenyaman penyajian data."""

plt.figure(figsize=(8, 4))
sns.barplot(data=country_sales.head(10), x="Quantity", y="Country", palette="rocket")
plt.title("Top 10 Negara dengan Volume Pembelian Terbesar")
plt.xlabel("Total Quantity")
plt.ylabel("Negara")
plt.tight_layout()
plt.show()

"""#Insight:
1. **Penjualan paling besar terpusat pada negara tertentu.** Mayoritas volume pembelian berasal dari satu atau dua negara utama, mencerminkan konsentrasi pasar.

2. **UK kemungkinan besar menjadi kontributor utama.** Hal ini dikarenakan banyaknya bisnis dari UK, maka wajar jika jumlah pembeliannya jauh lebih tinggi dari negara lain.

3. **Peluang ekspansi ke negara dengan volume menengah.** Negara dengan volume cukup tinggi (namun bukan teratas) dapat ditargetkan untuk promosi atau ekspansi pasar yang lebih masif.

4. **Negara dengan volume sangat kecil mungkin hanya mencerminkan satu atau dua pelanggan.** Ini menunjukkan pasar potensial yang belum tergarap atau hanya sebagai pembelian percobaan. Patut dipertimbangkan untuk konsentrasi pasar ke negara-negara tersebut

5. **Agregasi berdasarkan negara memberikan wawasan strategi distribusi** Banyaknya volume pembelian negara menunjukkan kebutuhan pasar yang akan mempengaruhi keputusan operasional, seperti kebutuhan terhadap gudang lokal, atau mana yang bisa dijangkau lewat partner reseller.

#Q4. Produk apa yang paling sering dibeli oleh masing-masing negara?

Sebelumnya hapus missing value dulu karena kita akan mengambil kolom 'Country', 'Description', dan 'Quatity' yang nantinya akan di 'groupby' dimana hal ini menjadi krusial, apabila ada data yang kosong, maka itu akan berpengaruh terhadap hasil yang diberikan (Moreover, it's also because I'm not sure, don't blame me)
"""

df_clean = df.dropna(subset=["Country", "Description", "Quantity"])
df_clean

country_product =  df_ready.groupby(["Country", "Description"])["Quantity"].sum().reset_index()

"""Hitung total quantity tiap produk per negara dengan dikelompokkan berdasarkan 'Country' dan 'Description' menggunakan 'groupby'. Tapi hasilnya akan menjadi 'MultiIndex', dimana datanya akan ada kemungkinan error sehingga perlu di reset menggunakan 'reset_index'"""

top_product_per_country = country_product.loc[country_product.groupby("Country")["Quantity"].idxmax()].sort_values(by="Quantity", ascending=False)
top_product_per_country.head(10)

"""Karena kita ingin melihat produk apa yang paling banyak dibeli oleh suatu negara, maka harus mengambil data produk pembelian paling atas dari masing-masing negara. <br><br>

Hasilnya ditampilkan dalam tabel diatas dalam 10 data teratas dengan alasan untuk mencapai titik fokus dalam kepuitusan bisnis yang lebih efektif, sehingga hanya memusatkan keputusan bisnis pada hal lebih urgent dibandingkan dengan hal lain. 10 data inilah yang akan divualisasikan.
"""

plt.figure(figsize=(8, 4))
sns.barplot(
    data=top_product_per_country.head(10),
    x="Quantity",
    y="Country",
    hue="Description",
    dodge=False,
    palette="viridis"
)
plt.title("Produk Terpopuler Berdasarkan Volume Pembelian per Negara (Top 10)")
plt.xlabel("Total Quantity")
plt.ylabel("Country")
plt.legend(title="Product", bbox_to_anchor=(1.05, 1), loc='upper left')
plt.tight_layout()
plt.show()

"""#Insight:
1. **Preferensi produk berbeda antar negara.** Setiap negara memiliki produk unggulan yang paling sering dibeli, mencerminkan minat atau kebutuhan yang spesifik. Sehingga akan mempengaruhi keputusan pemasaran yang dibutuhkan

2. **Produk teratas biasanya bernilai tinggi dalam jumlah pembelian.** Ini bisa jadi karena karakteristik produk yang populer untuk reseller atau stok besar. Ini akan mempengaruhi strategi pasar dan kesiapan operasional yang berlaku.

3. **Bisa jadi acuan untuk strategi regional.** Banyaknya suatu produk yang laku lebih banyak di negara yang berbeda menunjukan minat yang berbeda, sehingga memiliki pendekatan pemasarn yang berbeda, yang mampu berdampak pada startegi pemasaran yang berbeda juga.

4. **Mempermudah alokasi stok & distribusi.** Mengetahui produk terpopuler per negara membantu perusahaan merencanakan tindakan operasional lanjutan seperti keberadaan gudang lokal dan logistik lainnya.

#Q5. Produk apa yang paling banyak dibeli dalam jumlah besar (Quantity > 100)?

Sebelumnya, karena kita akan mengambil pembelian dalm jumlah besar, maka kita harus mengambil data yang memiliki data pembelian dengan Quantity diatas 100
"""

bulk_orders = df_ready[df_ready["Quantity"] > 100]
bulk_orders

"""Kode diatas juga digunakan untuk melakukan filtrasi terhadap data dimana data yang diambil hanya akan terpusat pada jumlah pembelian dengan Quantity diatas 100"""

bulk_top_products = bulk_orders.groupby("Description")["Quantity"].sum().sort_values(ascending=False).head(10).reset_index()
bulk_top_products.head(10)

"""Karena satu produk bisa muncul di banyak transaksi, kita perlu melakukan 'grouping' berdasarkan 'Description' agar semua pembelian untuk produk yang sama digabung. Kemudian, fungsi 'sum()' digunakan untuk menjumlahkan 'Quantity' dari masing-masing produk.<br><br>

Hasilnya ditampilkan dalam tabel diatas dalam 10 data teratas dengan alasan untuk mencapai titik fokus dalam kepuitusan bisnis yang lebih efektif, sehingga hanya memusatkan keputusan bisnis pada hal lebih urgent dibandingkan dengan hal lain. 10 data inilah yang akan divualisasikan.
"""

plt.figure(figsize=(8, 4))
sns.barplot(
    data=bulk_top_products.head(10),
    x="Quantity",
    y="Description",
    palette="magma"
)
plt.title("Top 10 Produk dengan Pembelian Jumlah Besar (Quantity > 100)")
plt.xlabel("Total Quantity")
plt.ylabel("Produk")
plt.tight_layout()
plt.show()

"""#Insight:
1. **Pembelian dalam jumlah besar bukan kebetulan.** Produk-produk yang muncul dalam daftar ini memiliki pola pembelian berulang dalam jumlah sangat besar, menunjukkan bahwa pelanggan memang secara konsisten membeli dalam skala besar, bukan sekadar outlier satu kali.

2. **Ciri khas produk untuk grosir, reseller, atau keperluan massal.** Jenis produk ini kemungkinan besar digunakan untuk stok toko, hadiah event, kebutuhan perusahaan, atau bahkan produksi ulang (misalnya, untuk kerajinan tangan atau paket ulang tahun).

3. **Penting untuk manajemen logistik & stok.** Produk-produk ini sebaiknya diprioritaskan dalam stok massal, dan gudang karena permintaannya besar dan bisa memengaruhi ketersediaan barang secara signifikan jika stok tidak diatur.

4. **Target pasar potensial: pembeli B2B** Pelanggan yang membeli dalam jumlah besar cenderung bukan konsumen biasa, melainkan bisnis kecil-menengah (SME), reseller, atau pihak ketiga. Ini membuka peluang strategi pemasaran dan layanan khusus seperti penawaran grosir, diskon tiered, atau akun pelanggan khusus.

## 3. Lakukan analisis multivariate pada kolom numerikal berupa :
- Correlation Heatmap + insight / observation **(10 poin)**

Sebelumnya kita ambil dahulu kolom numerikal, yaitu kolom yang tentunya memiliki nomor, yaitu yang bertipe 'float' dan 'int'
"""

numerical_df = df.select_dtypes(include=['float64', 'int64'])
numerical_df

"""Selanjutnya kita akan lakukan perhitungan korelasi antar kolom numerikal."""

correlation_matrix = numerical_df.corr()

"""Hal diatas dilakukan untuk mengetahui sejauh mana suatu kolom saling berhubungan satu sama lainnya, dan sejauh mana kedua variabel atau disebut dalam hal ini adalah 'kolom' bergerak bersama:
  - Nilai mendekati +1 → hubungan positif sempurna (jika satu naik, yang lain ikut naik).
  - Nilai -1 → hubungan negatif sempurna (jika satu naik, yang lain turun).
  - Nilai 0 → tidak ada hubungan linear.

Hasil perhitungan inilah yang akan divisualisasikan dalam heatmap
"""

plt.figure(figsize=(8, 4))
sns.heatmap(correlation_matrix, annot=True, cmap='coolwarm', fmt='.2f')
plt.title('Correlation Heatmap of Numerical Columns')
plt.tight_layout()
plt.show()

"""#INSIGHT:
1. **Terdapat Hubungan Erat antara Harga, Kuantitas, dan Nilai Transaksi**
- Korelasi Quantity dan UnitPrice sebesar 0.73 menunjukkan bahwa barang dengan jumlah besar cenderung memiliki harga lebih tinggi, atau ada kecenderungan bahwa volume tinggi tidak selalu karena diskon.
- TotalPrice sangat berkorelasi dengan Quantity (0.94) dan UnitPrice (0.90).
  - Ini logis karena TotalPrice = Quantity × UnitPrice, tapi juga menunjukkan bahwa kedua komponen tersebut sama-sama dominan dalam membentuk nilai transaksi.

2. **Tidak Ada Bukti Bahwa Harga Rendah Mendorong Pembelian Massal**
- Korelasi positif antara Quantity dan UnitPrice menandakan bahwa penurunan harga tidak menjadi pendorong utama pembelian dalam jumlah besar.
- Artinya:
  - Diskon atau harga murah bukan satu-satunya pemicu tingginya volume transaksi.
  - Faktor seperti kebutuhan besar, pembelian rutin, atau segmentasi konsumen (grosir vs retail) mungkin lebih berperan.

3. **TotalPrice Valid untuk Segmentasi Nilai Transaksi**
- Korelasi yang kuat dari TotalPrice terhadap kedua variabel dasar menjadikan metrik ini sangat representatif dalam analisis pelanggan bernilai tinggi, bundling produk, atau strategi diskon terarah..

# Implikasi Bisnis dan Strategi
1. **Fokus pada Produk Bernilai Tinggi, Bukan Sekadar Volume**
- Karena TotalPrice berkorelasi kuat baik dengan jumlah (Quantity) maupun harga (UnitPrice), maka:
  - Strategi: Prioritaskan produk yang memiliki harga relatif tinggi dan laku dalam jumlah besar.
- Tidak semua volume besar berasal dari diskon → jangan hanya promosi ke produk termurah.
- Segmentasi harga premium tetap layak untuk ditawarkan ke pembeli besar.

2. **Optimalisasi Penawaran Bundling & Grosir**
- Korelasi antara Quantity dan UnitPrice cukup tinggi (+0.73):
  - Menunjukkan produk mahal juga dibeli dalam jumlah besar, bisa jadi oleh pembeli bisnis/reseller.
- Strategi: Tawarkan paket bundling atau skema grosir untuk produk-produk dengan margin tinggi.
- Hal ini cocok untuk:
  - Bulk buyer
  - Langganan tetap (subscription)
  - Pelanggan loyal dengan pembelian berulang

3. **Gunakan TotalPrice untuk Segmentasi dan Targeting**
- Karena TotalPrice merepresentasikan nilai transaksi sebenarnya dan sangat korelatif, kamu bisa:
  - Strategi: Bangun model segmentasi pelanggan berdasarkan total belanja (TotalPrice)
- Ini berguna untuk:
  - Memberikan penawaran eksklusif ke high spenders
  - Menyusun program loyalitas
  - Menyesuaikan biaya akuisisi pelanggan secara efisien

4. **Evaluasi Peran Diskon — Tidak Selalu Efektif**
- Korelasi tidak negatif antara UnitPrice dan Quantity → diskon bukan faktor utama volume.
- Strategi: Fokus pada value-driven marketing, bukan price-cutting semata.
- Gunakan pendekatan promosi yang menekankan:
  - Kualitas produk
  - Relevansi penggunaan (seasonal, kebutuhan khusus)
  - Bundle yang meningkatkan perceived value

## 4. Tuliskan kesimpulan dari Case Study EDA tersebut

#KESIMPULAN AKHIR:
1. Data Understanding
  - Dataset terdiri dari data transaksi penjualan online, termasuk kolom seperti InvoiceNo, Description, Quantity, InvoiceDate, UnitPrice, CustomerID, dan Country.
  - Ditemukan adanya missing values di beberapa kolom penting (Description, CustomerID, Country), yang harus dibersihkan untuk analisis yang akurat.
  - Data memiliki format waktu (InvoiceDate) yang perlu dikonversi ke format datetime agar dapat dimanipulasi berdasarkan waktu.

2. Feature Engineering
  - Dihapus baris dan kolom dengan data kosong dan tidak perlu di kolom kunci agar grouping tidak menghasilkan noise.
  - Dilakukan konversi InvoiceDate ke format datetime untuk kebutuhan analisis berbasis waktu.
  - Dibuat kolom Month dari InvoiceDate untuk analisis tren penjualan per bulan.
  - (Opsional) Dibuat kolom TotalPrice = Quantity * UnitPrice untuk potensi analisis pendapatan.

3. Analisis Berdasarkan Pertanyaan (1–5)
  1. Pertanyaan 1: Produk apa yang paling banyak terjual?
    - Dilakukan agregasi total Quantity per Description.
    - Produk terlaris ternyata memiliki volume tinggi, mengindikasikan potensi bundling, diskon, atau pengulangan pembelian.

  2. Pertanyaan 2: Pola pembelian bulanan seperti apa?
    - Dikelompokkan berdasarkan Month dan dijumlahkan total Quantity.
    - Terlihat adanya fluktuasi penjualan, dan potensi lonjakan di bulan tertentu (misalnya menjelang akhir tahun).

  3. Pertanyaan 3: Negara mana yang paling banyak membeli?
    - Data dikelompokkan berdasarkan Country, diurutkan berdasarkan total Quantity.
    - Terlihat bahwa mayoritas penjualan berasal dari beberapa negara dominan, sedangkan negara lain berkontribusi kecil.

  4.  Pertanyaan 4: Produk apa yang paling populer di setiap negara?
    - Dikelompokkan berdasarkan kombinasi Country dan Description, kemudian dihitung total Quantity.
    - Diperlukan pembersihan data sebelum analisis karena kombinasi ini sangat sensitif terhadap missing value.

  5.  Pertanyaan 5: Produk apa yang paling sering dibeli dalam jumlah besar (Quantity > 100)?
    - Difilter data untuk transaksi besar, lalu di-group berdasarkan Description.
    - Mengungkap produk-produk dengan permintaan dalam jumlah besar yang cocok untuk strategi grosir atau pelanggan B2B.

#Insight Umum (Gabungan dari Semua Pertanyaan)
  1. Permintaan terpusat pada produk tertentu — Terlihat konsistensi permintaan tinggi untuk beberapa produk, baik di level global maupun per negara.

  2. Banyak pembelian massal: Transaksi besar menunjukkan adanya pembeli tipe grosir/reseller yang berbeda dari pelanggan eceran biasa.

  3. Tren waktu penting untuk strategi: Analisis per bulan menunjukkan musim penjualan yang dapat dimanfaatkan untuk promosi atau pengelolaan stok.

  4. Negara tertentu mendominasi penjualan: Mengindikasikan pasar inti yang bisa difokuskan untuk ekspansi, pemasaran, atau pengiriman lokal.

  5. Filtering transaksi besar mengungkap insight tersembunyi: Dengan menyaring data berdasarkan Quantity > 100, terlihat produk-produk kunci yang berkontribusi signifikan pada total volume.
"""

